import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
    en: {
        // Nav & Layout
        homeNav: 'Home',
        services: 'Services Overview',
        aiAssistant: 'AI Assistant',
        specialists: 'Specialists',
        about: 'About Us',
        bookBtn: 'Book Consultation',
        learnMore: 'Learn More',
        langLabel: 'Language',

        // Home – Hero
        heroTitle1: 'World-Class Medical',
        heroTitle2: 'Concierge',
        heroSubtitle: 'Experience end-to-end luxury patient care and international medical tourism services tailored for your peace of mind.',
        premiumCare: 'Premium Care',
        heroBtn1: 'Request Second Opinion',
        heroBtn2: 'Our Services',

        // Home – Journey
        journeyLabel: 'Your Care Journey',
        journeyTitle: 'Seamless Home-to-Hospital Support',
        journeyDesc: 'From your doorstep to the hospital and back, we handle every logistical detail so you can focus entirely on healing.',
        viewFullJourney: 'View Full Journey',
        step1Title: 'Pre-Arrival Planning',
        step1Desc: 'Tele-consultations with specialists and personalized itinerary creation tailored to your medical needs before you even leave home.',
        step2Title: 'VIP Hospital Admission',
        step2Desc: 'Express check-in via private entrance, luxury private suites, and dedicated multilingual liaisons by your side 24/7.',
        step3Title: 'Post-Care Recovery',
        step3Desc: 'Comprehensive follow-up care plans, medication delivery to your accommodation, and safe medical transport home.',

        // Home – International Patient Services
        exclusiveBenefits: 'Exclusive Benefits',
        intlPatientsTitle: 'International Patient Services',
        intlPatientsDesc: 'We bridge the gap between borders. Our dedicated international team ensures language is never a barrier and comfort is always a priority.',
        airportMeetTitle: 'Airport Meet & Greet',
        airportMeetDesc: 'Personal assistant waiting at the gate for fast-track immigration.',
        medicalInterpTitle: 'Medical Interpretation',
        medicalInterpDesc: 'Certified interpreters available in over 15 languages.',
        vipTransportTitle: 'VIP Transport',
        vipTransportDesc: 'Luxury sedan or limousine service for all local travel.',
        insuranceLiaisonTitle: 'Insurance Liaison',
        insuranceLiaisonDesc: 'Direct billing coordination with international insurance providers.',
        viewPackages: 'View Concierge Packages',
        whiteGlove: 'White Glove Service',
        priorityTransfer: 'Priority Airport Transfer',
        jciAccred: 'JCI Accredited',
        jciStandard: 'International Quality Standards',

        // Home – CTA
        homeCtaTitle: 'Ready to Experience Premium Care?',
        homeCtaDesc: 'Our medical specialists are ready to provide you with a comprehensive second opinion and a personalized treatment plan.',
        homeCtaBtn1: 'Book Consultation',
        homeCtaBtn2: 'Contact Specialist',
        homeCtaNote: 'Operating 24/7 • Global Assistance Center • Confidential',

        // Services page
        servicesHeroTitle: 'Our Medical Service Ecosystem',
        servicesHeroDesc: 'Comprehensive end-to-end patient management and premium international medical tourism solutions tailored to your needs. Experience healthcare without borders.',
        exploreServices: 'Explore Services',
        viewDoctors: 'View Doctors',
        specializedCareLabel: 'Specialized Care Pillars',
        specializedCareDesc: 'Navigate your healthcare journey with our integrated suite of premium services designed for peace of mind and optimal outcomes.',
        s1Title: 'Specialist Coordination',
        s1Desc: 'We connect you with world-renowned specialists perfectly matched to your specific medical condition using our proprietary matching algorithm.',
        s2Title: 'Second Opinion & Evaluation',
        s2Desc: 'Expert re-evaluation of diagnoses and transparent price comparisons to ensure the best care value and treatment efficacy.',
        s3Title: 'Advanced Therapies',
        s3Desc: 'Access cutting-edge treatments including Stem Cell Therapy and regenerative medicine protocols unavailable in standard care.',
        s4Title: 'Post-Surgery Nursing',
        s4Desc: 'Professional nursing care delivered in comfort, ensuring a safe and smooth recovery process with 24/7 monitoring capabilities.',
        s5Title: 'VIP Logistics',
        s5Desc: 'Seamless travel arrangements including private airport transfers, home pickup, and luxury accommodation management.',
        s6Title: '24/7 Concierge Support',
        s6Desc: 'Dedicated care coordinators available round-the-clock to handle any request, from translation to family accommodation.',
        planJourneyTitle: 'Plan Your Medical Journey',
        planJourneyDesc: 'Use our interactive tool to get an immediate estimate of your treatment and concierge service costs.',

        // Cost Estimator
        ceTitle: 'Interactive Cost Estimator',
        ceDesc: 'Get a transparent estimate for your medical journey.',
        ceEstimatedCost: 'Estimated Cost',
        ceStep1Title: 'What type of care are you seeking?',
        ceOrthopedic: 'Orthopedic Surgery',
        ceCardiac: 'Cardiac Care',
        ceStemCell: 'Stem Cell Therapy',
        ceCosmetic: 'Cosmetic / Plastic',
        ceDental: 'Dental Procedures',
        ceOther: 'Other Treatment',
        ceStep2Title: 'Select Concierge Add-ons',
        ceTransportTitle: 'VIP Ground Transport',
        ceTransportDesc: 'Airport meet & greet, priority immigration, and all local hospital transfers in a luxury van.',
        ceNursingTitle: 'Post-Surgery Nursing (1 Week)',
        ceNursingDesc: 'Private registered nurse at your hotel to assist with recovery, medications, and wound care.',
        ceInterpTitle: 'Dedicated Medical Interpreter',
        ceInterpDesc: 'Native speaker to accompany you to all consultations and translate medical documents.',
        ceStep3Title: 'Estimate Complete',
        ceStep3Desc: 'This is a preliminary estimate. Please book a consultation with our specialists to review your actual medical files for an exact quote.',
        ceProceedBtn: 'Proceed to Consultation',
        ceBack: 'Back',
        ceContinue: 'Continue',

        servicesCtaTitle: 'Ready to start your journey?',
        servicesCtaDesc: 'Contact our dedicated care team today for a personalized consultation and let us handle the complexities of your medical care.',
        contactSupport: 'Contact Support',
        learnAboutUs: 'Learn More About Us',

        // Specialists page
        ourMedicalTeam: 'Our Medical Team',
        specialistsHeroTitle: 'World-Class Specialists',
        specialistsHeroDesc: 'Our network of internationally accredited physicians bring decades of expertise to every case. Browse and connect directly with the right specialist for your condition.',
        jciAccredited: 'JCI Accredited',
        langs15: '15+ Languages',
        specialists50Plus: '50+ Specialists',
        searchPlaceholder: 'Search by name or specialty...',
        availableNow: 'Available Now',
        filterAll: 'All Specialties',
        filterCardiology: 'Cardiology',
        filterOrthopedics: 'Orthopedics',
        filterOncology: 'Oncology',
        filterNeurology: 'Neurology',
        filterStemCell: 'Stem Cell',
        filterCosmetic: 'Cosmetic',
        statusAvailable: 'Available',
        statusBooked: 'Booked',
        bookConsultation: 'Book Consultation',
        joinWaitlist: 'Join Waitlist',
        noSpecialistsFound: 'No specialists found.',
        adjustSearch: 'Try adjusting your search or filters.',
        specialistCtaTitle: 'Not sure which specialist is right for you?',
        specialistCtaDesc: 'Our care team can analyze your condition and recommend the most suitable specialist from our network.',

        // About page
        ourStory: 'Our Story',
        aboutTitle1: 'Redefining',
        aboutTitle2: 'Medical Tourism',
        aboutDesc1: 'Founded in Bangkok in 2015, Bio Connext was born from a simple belief: every patient deserves world-class healthcare without the complexity, confusion, or cost barriers that so often stand in the way.',
        aboutDesc2: 'We bridged the gap between internationally-trained specialists and patients around the world who need them — with a commitment to luxury, transparency, and genuine human care.',
        estYear: 'Est. 2015',
        estCity: 'Bangkok, Thailand',
        yearsExcellence: '10 Years of Excellence',
        trustedPatients: 'Trusted by patients in 45+ countries',
        patientsServed: 'Patients Served',
        countriesReached: 'Countries Reached',
        specialistPartners: 'Specialist Partners',
        averageRating: 'Average Rating',
        ourMission: 'Our Mission',
        whyWeExist: 'Why We Exist',
        missionDesc: 'We exist to remove every barrier between a patient and the care they deserve — whether that barrier is language, logistics, cost transparency, or simply knowing where to start.',
        v1Title: 'Patient-First Philosophy',
        v1Desc: 'Every decision we make is guided by what is best for the patient — not convenience, not cost, but care.',
        v2Title: 'Radical Transparency',
        v2Desc: 'We believe in clear pricing, honest assessments, and open communication throughout your entire journey.',
        v3Title: 'Cultural Sensitivity',
        v3Desc: 'Our multilingual team understands that great care means meeting patients in their own language and culture.',
        v4Title: 'Evidence-Based Excellence',
        v4Desc: 'We partner only with internationally accredited hospitals and physicians with proven clinical track records.',
        peopleBehind: 'The People Behind the Care',
        leadershipTeam: 'Our Leadership Team',
        partnersLabel: 'Our Partners & Accreditations',
        aboutCtaTitle: 'Ready to Start Your Journey?',
        aboutCtaDesc: 'Join thousands of patients who trusted Bio Connext to navigate their most important health decisions.',
        meetSpecialists: 'Meet Our Specialists',

        // AI Assistant page
        aiBrandTagline: 'Premium Medical Assistance',
        aiNewConsult: 'New Consultation',
        aiMenuLabel: 'Menu',
        aiRecentConsults: 'Recent Consultations',
        aiHealthProfile: 'My Health Profile',
        aiMedRecords: 'Medical Records',
        aiViewSpecialists: 'View Specialists',
        aiRecentHistory: 'Recent History',
        aiBackHome: 'Back to Home',
        aiEmergencyContacts: 'Emergency Contacts',
        aiOnlineStatus: 'Online · Multilingual',
        aiEmergencyBtn: 'Emergency',
        aiYou: 'You',
        aiDrName: 'Dr. AI Concierge',
        aiTypePlaceholder: 'Describe your medical needs or ask a question…',
        aiEncryptedNote: 'End-to-end encrypted · HIPAA compliant',
        aiDisclaimerNote: 'AI may make mistakes — verify critical medical info with specialists.',
        aiEmergencyAvailable: 'Available 24/7',
        aiClose: 'Close',
        aiToday: 'Today',
        aiYesterday: 'Yesterday',
        aiHistory1: 'Cardiac Second Opinion',
        aiHistory2: 'Dermatology Referral',
        aiHistory3: 'Hip Replacement Inquiry',

        // Stats bar
        statPatients: 'Patients Served',
        statCountries: 'Countries',
        statSpecialists: 'Specialists',
        statRating: 'Patient Rating',

        // Trust section
        trustLabel: 'Trusted Worldwide',
        trustTitle: 'World-Class Accreditations',
        trustDesc: 'We partner exclusively with internationally accredited hospitals, ensuring you receive care that meets the highest global standards.',
        trustJciTitle: 'JCI Accredited',
        trustJciDesc: 'Gold standard in global healthcare quality and patient safety.',
        trustIsoTitle: 'ISO 9001:2015',
        trustIsoDesc: 'Certified quality management systems across all operations.',
        trustTemosTitle: 'TEMOS Certified',
        trustTemosDesc: 'International quality assurance for medical tourism.',

        // Testimonials
        testimonialsLabel: 'Patient Stories',
        testimonialsTitle: 'What Our Patients Say',
        testimonialsDesc: 'Real experiences from patients who trusted Bio Connext for their medical journey.',
        testimonial1Name: 'James Miller',
        testimonial1Location: 'United States',
        testimonial1Text: 'From the moment I landed in Bangkok, the Bio Connext team made me feel completely at ease. My cardiac surgery was world-class, and the aftercare was beyond anything I experienced back home.',
        testimonial2Name: 'Yuki Tanaka',
        testimonial2Location: 'Japan',
        testimonial2Text: 'The Japanese interpreter assigned to me understood every medical term perfectly. The cost savings were incredible — I paid 60% less than quotes from Tokyo hospitals for the same procedure.',
        testimonial3Name: 'Sarah Al-Rashid',
        testimonial3Location: 'UAE',
        testimonial3Text: 'Bio Connext coordinated everything: flights, hotel, hospital transfers, even meals. The stem cell therapy results have been life-changing. I cannot recommend them enough.',

        // FAQ Section
        faqTitle: 'Frequently Asked Questions',
        faqSubtitle: 'Everything you need to know about medical tourism in Thailand',
        faq1Q: 'What is medical tourism in Thailand?',
        faq1A: 'Medical tourism in Thailand involves international patients traveling to Thailand for healthcare services. Thailand is a global leader in medical tourism, offering JCI-accredited hospitals, board-certified specialists, and costs 40–70% lower than Western countries. Bio Connext coordinates the entire journey from specialist matching to post-treatment recovery.',
        faq2Q: 'How much does medical treatment cost in Thailand compared to the US?',
        faq2A: 'Medical procedures in Thailand typically cost 40–70% less than in the United States. For example, cardiac surgery may cost $15,000–$25,000 in Thailand versus $70,000–$150,000 in the US. Orthopedic procedures, dental work, and cosmetic surgery offer similar savings — all at JCI-accredited facilities with internationally trained surgeons.',
        faq3Q: 'What services does Bio Connext provide?',
        faq3A: 'Bio Connext provides end-to-end medical concierge services including: specialist doctor matching from 50+ partners, second medical opinions, airport meet-and-greet, VIP medical transport, medical interpretation in 10+ languages, insurance liaison, post-surgery nursing care, accommodation arrangements, and 24/7 multilingual concierge support.',
        faq4Q: 'Are hospitals in Thailand internationally accredited?',
        faq4A: 'Yes, Thailand has over 60 JCI (Joint Commission International) accredited hospitals — more than any other country in Asia. Bio Connext partners exclusively with JCI-accredited, ISO 9001:2015 certified, and TEMOS-certified facilities to ensure the highest standards of patient safety and quality.',
        faq5Q: 'What languages are supported for medical interpretation?',
        faq5A: 'Bio Connext provides professional medical interpretation in over 10 languages including English, Thai, Mandarin Chinese, Japanese, Arabic, Russian, German, French, Korean, and Spanish. Medical interpreters are certified and experienced in healthcare terminology.',

        // AI Assistant – greeting & suggestions
        aiGreeting: 'Hello! Sawasdee krub! Ni hao!',
        aiWelcomeMsg: 'I am your personal medical concierge. How can I assist with your health journey today?',
        aiHelpIntro: 'I can help with:',
        aiHelpItem1: 'Booking specialist appointments',
        aiHelpItem2: 'Arranging VIP airport transport',
        aiHelpItem3: 'Processing & translating medical records',
        aiHelpItem4: 'Requesting second opinions',
        aiHelpItem5: 'Cost estimates & concierge packages',
        aiSuggestion1: 'Book Appointment',
        aiSuggestion2: 'Second Opinion',
        aiSuggestion3: 'Airport Transport',
        aiSuggestion4: 'Upload Records',
        aiSidebarConsults: 'Recent Consultations',
        aiSidebarProfile: 'My Health Profile',
        aiSidebarRecords: 'Medical Records',
        aiSidebarEmergency: 'Emergency Contacts',
        aiEmergencyTitle: 'Emergency Contacts',
        aiEmergencyDesc: 'Available 24/7',

        // Pricing page
        pricingNav: 'Pricing',
        pricingHeroTitle: 'Transparent Pricing',
        pricingHeroDesc: 'Choose the concierge package that fits your medical journey. All packages include access to JCI-accredited hospitals and our specialist network.',
        pricingMostPopular: 'Most Popular',
        pricingBasicName: 'Essential',
        pricingBasicPrice: '$2,500',
        pricingBasicDesc: 'Perfect for straightforward procedures with standard support.',
        pricingBasicF1: 'Specialist matching & referral',
        pricingBasicF2: 'Airport pickup (economy sedan)',
        pricingBasicF3: 'Medical interpretation (English)',
        pricingBasicF4: 'Hospital admission coordination',
        pricingBasicF5: 'Basic follow-up support (7 days)',
        pricingPremiumName: 'Premium',
        pricingPremiumPrice: '$5,500',
        pricingPremiumDesc: 'Comprehensive care with VIP logistics and dedicated coordinator.',
        pricingPremiumF1: 'Everything in Essential, plus:',
        pricingPremiumF2: 'VIP airport meet & greet + fast-track immigration',
        pricingPremiumF3: 'Luxury sedan transfers (unlimited)',
        pricingPremiumF4: 'Dedicated multilingual coordinator 24/7',
        pricingPremiumF5: 'Post-surgery nursing care (1 week)',
        pricingPremiumF6: 'Insurance liaison & billing support',
        pricingPremiumF7: 'Hotel/accommodation arrangement',
        pricingVipName: 'VIP Concierge',
        pricingVipPrice: '$12,000',
        pricingVipDesc: 'The ultimate white-glove medical experience, fully personalized.',
        pricingVipF1: 'Everything in Premium, plus:',
        pricingVipF2: 'Private jet/helicopter transfer option',
        pricingVipF3: 'Private hospital suite upgrade',
        pricingVipF4: 'Personal chef & dietary management',
        pricingVipF5: 'Family accommodation & concierge',
        pricingVipF6: 'Extended recovery support (30 days)',
        pricingVipF7: '2nd opinion from international specialist',
        pricingVipF8: 'Priority scheduling at all partner hospitals',
        pricingSelectPlan: 'Select Plan',
        pricingContactUs: 'Contact Us',
        pricingNoteTitle: 'What\'s not included?',
        pricingNoteDesc: 'Package prices cover concierge services only. Actual medical procedure costs vary by treatment type and hospital. Use our Cost Estimator for procedure pricing.',
        pricingPerPackage: 'per package',

        // Payment page
        paymentTitle: 'Complete Your Booking',
        paymentOrderSummary: 'Order Summary',
        paymentPlan: 'Plan',
        paymentTotal: 'Total',
        paymentMethodTitle: 'Select Payment Method',
        paymentCreditCard: 'Credit / Debit Card',
        paymentPromptPay: 'PromptPay QR',
        paymentBankTransfer: 'Bank Transfer',
        paymentCardNumber: 'Card Number',
        paymentExpiry: 'Expiry (MM/YY)',
        paymentCvc: 'CVC',
        paymentCardHolder: 'Cardholder Name',
        paymentPayNow: 'Pay Now',
        paymentProcessing: 'Processing...',
        paymentScanQr: 'Scan QR code with your banking app',
        paymentQrExpiry: 'QR code expires in 15 minutes',
        paymentBankName: 'Bank Name',
        paymentBankAccount: 'Account Number',
        paymentBankHolder: 'Account Holder',
        paymentBankRef: 'Reference',
        paymentBankInstructions: 'Transfer the exact amount and use the reference code. Send transfer slip to contact@bio.techdev.in.th for confirmation.',
        paymentSecure: 'All transactions are encrypted and secure',
        paymentSuccess: 'Payment Successful!',
        paymentSuccessDesc: 'Your booking has been confirmed. We will contact you within 24 hours to begin your medical journey.',
        paymentBackHome: 'Back to Home',
        paymentNoPlan: 'No plan selected',
        paymentNoPlanDesc: 'Please select a package from our pricing page first.',
        paymentGoToPricing: 'View Pricing',

        // Footer
        footerDesc: 'Your trusted partner in international medical tourism and premium healthcare management.',
        footerServices: 'Services',
        footerContact: 'Contact',
        footerAiConcierge: 'AI Concierge',
        footerPrivacy: 'Privacy Policy',
        footerTerms: 'Terms of Service',
        footerCopyright: '© 2025 Bio Connext. All rights reserved.',

        // NotFound page
        notFoundTitle: '404',
        notFoundHeading: 'Page Not Found',
        notFoundDesc: "The page you're looking for doesn't exist or has been moved.",
        notFoundHome: 'Back to Home',
        notFoundAi: 'Ask AI Assistant',

        // BookingModal
        bookingSubtitle: 'Fill in your details and we will contact you',
        bookingThankYou: 'Thank you!',
        bookingSuccessDesc: "We'll contact you within 24 hours.",
        bookingLabelName: 'Full Name',
        bookingLabelEmail: 'Email',
        bookingLabelPhone: 'Phone',
        bookingLabelSpecialty: 'Condition / Specialty',
        bookingSelectSpecialty: 'Select a specialty...',
        bookingLabelDate: 'Preferred Date',
        bookingLabelNotes: 'Additional Notes',
        bookingErrName: 'Name is required',
        bookingErrEmailReq: 'Email is required',
        bookingErrEmailValid: 'Please enter a valid email',
        bookingErrPhone: 'Phone number is required',
        bookingErrSpecialty: 'Please select a specialty',
        bookingErrDate: 'Please select a date',

        // Theme toggle
        themeLight: 'Switch to Light Mode',
        themeDark: 'Switch to Dark Mode',
    },

    th: {
        // Nav & Layout
        homeNav: 'หน้าหลัก',
        services: 'บริการของเรา',
        aiAssistant: 'AI Assistant',
        specialists: 'แพทย์ผู้เชี่ยวชาญ',
        about: 'เกี่ยวกับเรา',
        bookBtn: 'นัดปรึกษาแพทย์',
        learnMore: 'ดูข้อมูลเพิ่มเติม',
        langLabel: 'ภาษา',

        // Home – Hero
        heroTitle1: 'บริการดูแลสุขภาพ',
        heroTitle2: 'ระดับพรีเมียม',
        heroSubtitle: 'บริการดูแลผู้ป่วยระดับ VIP และท่องเที่ยวเชิงสุขภาพนานาชาติแบบครบวงจร ให้คุณวางใจได้ทุกขั้นตอน',
        premiumCare: 'บริการระดับพรีเมียม',
        heroBtn1: 'ขอ Second Opinion',
        heroBtn2: 'ดูบริการทั้งหมด',

        // Home – Journey
        journeyLabel: 'ขั้นตอนการดูแลของคุณ',
        journeyTitle: 'ดูแลทุกขั้นตอน ตั้งแต่บ้านถึงโรงพยาบาล',
        journeyDesc: 'ตั้งแต่หน้าบ้านจนถึงโรงพยาบาลและกลับบ้าน เราจัดการทุกอย่างให้คุณ เพื่อให้คุณโฟกัสกับการพักฟื้นได้อย่างเต็มที่',
        viewFullJourney: 'ดูขั้นตอนทั้งหมด',
        step1Title: 'วางแผนก่อนเดินทาง',
        step1Desc: 'ปรึกษาแพทย์ผู้เชี่ยวชาญทางออนไลน์ และจัดทำแผนการรักษาส่วนตัวให้เหมาะกับคุณก่อนออกเดินทาง',
        step2Title: 'เข้าพัก รพ. แบบ VIP',
        step2Desc: 'เช็คอินด่วนทางเข้าส่วนตัว ห้องพักระดับหรู พร้อมล่ามหลายภาษาดูแลตลอด 24 ชั่วโมง',
        step3Title: 'ดูแลต่อเนื่องหลังการรักษา',
        step3Desc: 'แผนติดตามผลครอบคลุม จัดส่งยาถึงที่พัก พร้อมรถรับส่งทางการแพทย์กลับบ้านอย่างปลอดภัย',

        // Home – International Patient Services
        exclusiveBenefits: 'สิทธิพิเศษสำหรับคุณ',
        intlPatientsTitle: 'บริการผู้ป่วยต่างประเทศ',
        intlPatientsDesc: 'เราดูแลให้ภาษาไม่ใช่อุปสรรค ทีมงานนานาชาติของเราพร้อมให้ความสะดวกสบายเป็นหัวใจของทุกบริการ',
        airportMeetTitle: 'รับที่สนามบิน',
        airportMeetDesc: 'เจ้าหน้าที่ส่วนตัวรอรับที่ประตูทางออก ช่วยผ่านด่านตรวจคนเข้าเมืองได้อย่างรวดเร็ว',
        medicalInterpTitle: 'ล่ามทางการแพทย์',
        medicalInterpDesc: 'ล่ามที่ได้รับการรับรองพร้อมให้บริการในกว่า 15 ภาษา',
        vipTransportTitle: 'รถรับส่ง VIP',
        vipTransportDesc: 'รถซีดานหรือลีมูซีนระดับหรูสำหรับการเดินทางทุกเส้นทาง',
        insuranceLiaisonTitle: 'ประสานงานประกัน',
        insuranceLiaisonDesc: 'ประสานงานเบิกประกันโดยตรงกับบริษัทประกันต่างประเทศของคุณ',
        viewPackages: 'ดูแพ็กเกจทั้งหมด',
        whiteGlove: 'บริการพิเศษสุดระดับ VIP',
        priorityTransfer: 'รับส่งสนามบินแบบด่วนพิเศษ',
        jciAccred: 'ได้รับการรับรอง JCI',
        jciStandard: 'มาตรฐานสากลระดับโลก',

        // Home – CTA
        homeCtaTitle: 'พร้อมรับการดูแลระดับพรีเมียมแล้วหรือยัง?',
        homeCtaDesc: 'ทีมแพทย์ผู้เชี่ยวชาญของเราพร้อมให้คำแนะนำและออกแบบแผนการรักษาเฉพาะสำหรับคุณ',
        homeCtaBtn1: 'นัดปรึกษาแพทย์',
        homeCtaBtn2: 'ติดต่อผู้เชี่ยวชาญ',
        homeCtaNote: 'เปิดบริการตลอด 24/7 • ศูนย์ดูแลทั่วโลก • เป็นความลับ',

        // Services page
        servicesHeroTitle: 'บริการทางการแพทย์ครบวงจร',
        servicesHeroDesc: 'บริการจัดการดูแลผู้ป่วยและท่องเที่ยวเชิงสุขภาพระดับพรีเมียม ออกแบบมาเพื่อตอบทุกความต้องการของคุณ สัมผัสการดูแลสุขภาพที่ไร้ข้อจำกัด',
        exploreServices: 'สำรวจบริการ',
        viewDoctors: 'ดูรายชื่อแพทย์',
        specializedCareLabel: 'บริการดูแลเฉพาะทาง',
        specializedCareDesc: 'ชุดบริการพรีเมียมครบวงจร ออกแบบมาเพื่อความสบายใจและผลลัพธ์การรักษาที่ดีที่สุด',
        s1Title: 'จับคู่กับผู้เชี่ยวชาญ',
        s1Desc: 'เราหาแพทย์ผู้เชี่ยวชาญระดับโลกที่ตรงกับอาการของคุณมากที่สุด ด้วยระบบจับคู่เฉพาะของเรา',
        s2Title: 'ขอ Second Opinion',
        s2Desc: 'ผู้เชี่ยวชาญตรวจสอบผลวินิจฉัยซ้ำและเปรียบเทียบราคาอย่างโปร่งใส เพื่อให้คุณได้รับการรักษาที่คุ้มค่าที่สุด',
        s3Title: 'การรักษาขั้นสูง',
        s3Desc: 'เข้าถึงการรักษานวัตกรรมใหม่ อาทิ สเต็มเซลล์ และการแพทย์ฟื้นฟู ที่ไม่มีในโรงพยาบาลทั่วไป',
        s4Title: 'พยาบาลดูแลหลังผ่าตัด',
        s4Desc: 'พยาบาลวิชาชีพดูแลคุณในสภาพแวดล้อมที่สะดวกสบาย รับรองการฟื้นตัวที่ปลอดภัยพร้อมติดตามผลตลอด 24 ชั่วโมง',
        s5Title: 'จัดการเดินทาง VIP',
        s5Desc: 'ครอบคลุมรถรับส่งสนามบินส่วนตัว รับถึงบ้าน และจัดการที่พักระดับหรูให้ครบทุกอย่าง',
        s6Title: 'ดูแลตลอด 24 ชั่วโมง',
        s6Desc: 'ทีมประสานงานพร้อมรับเรื่องตลอดเวลา ตั้งแต่งานล่ามภาษาไปจนถึงจัดหาที่พักให้ครอบครัว',
        planJourneyTitle: 'วางแผนการรักษาของคุณ',
        planJourneyDesc: 'ลองใช้เครื่องมือของเราคำนวณค่าใช้จ่ายโดยประมาณสำหรับการรักษาและบริการเสริมได้เลย',

        // Cost Estimator
        ceTitle: 'คำนวณค่าใช้จ่ายเบื้องต้น',
        ceDesc: 'ประมาณค่าใช้จ่ายการรักษาและบริการเสริมได้อย่างโปร่งใส',
        ceEstimatedCost: 'ค่าใช้จ่ายโดยประมาณ',
        ceStep1Title: 'คุณต้องการรับการรักษาด้านใด?',
        ceOrthopedic: 'ผ่าตัดกระดูกและข้อ',
        ceCardiac: 'โรคหัวใจ',
        ceStemCell: 'สเต็มเซลล์บำบัด',
        ceCosmetic: 'ศัลยกรรมความงาม',
        ceDental: 'ทันตกรรม',
        ceOther: 'การรักษาอื่นๆ',
        ceStep2Title: 'เลือกบริการเสริมที่ต้องการ',
        ceTransportTitle: 'รถรับส่ง VIP',
        ceTransportDesc: 'รับที่สนามบิน ช่วยด่านตรวจคนเข้าเมือง พร้อมรถแวนพรีเมียมรับส่งระหว่างโรงพยาบาล',
        ceNursingTitle: 'พยาบาลดูแลหลังผ่าตัด (1 สัปดาห์)',
        ceNursingDesc: 'พยาบาลวิชาชีพดูแลคุณที่โรงแรม ครอบคลุมการพักฟื้น การจัดการยา และการทำแผล',
        ceInterpTitle: 'ล่ามประจำตัว',
        ceInterpDesc: 'ล่ามเจ้าของภาษาดูแลคุณตลอดการนัดพบแพทย์ พร้อมแปลเอกสารทางการแพทย์ทุกฉบับ',
        ceStep3Title: 'ผลการประมาณค่าใช้จ่าย',
        ceStep3Desc: 'นี่คือตัวเลขประมาณการเบื้องต้น กรุณานัดหมายปรึกษากับแพทย์ผู้เชี่ยวชาญเพื่อรับใบเสนอราคาที่แม่นยำ',
        ceProceedBtn: 'นัดหมายปรึกษา',
        ceBack: 'ย้อนกลับ',
        ceContinue: 'ถัดไป',

        servicesCtaTitle: 'พร้อมเริ่มต้นแล้วหรือยัง?',
        servicesCtaDesc: 'ติดต่อทีมของเราวันนี้เพื่อรับคำปรึกษาส่วนตัว แล้วปล่อยให้เราดูแลทุกขั้นตอนให้คุณ',
        contactSupport: 'ติดต่อเรา',
        learnAboutUs: 'รู้จักเราให้มากขึ้น',

        // Specialists page
        ourMedicalTeam: 'ทีมแพทย์ของเรา',
        specialistsHeroTitle: 'แพทย์ผู้เชี่ยวชาญระดับโลก',
        specialistsHeroDesc: 'เครือข่ายแพทย์ผู้เชี่ยวชาญที่ได้รับการรับรองระดับนานาชาติ พร้อมให้คุณค้นหาและนัดหมายได้โดยตรง',
        jciAccredited: 'ได้รับการรับรอง JCI',
        langs15: 'รองรับกว่า 15 ภาษา',
        specialists50Plus: 'แพทย์ผู้เชี่ยวชาญ 50+ คน',
        searchPlaceholder: 'ค้นหาชื่อแพทย์หรือสาขาเฉพาะทาง...',
        availableNow: 'พร้อมรับนัดตอนนี้',
        filterAll: 'ทุกสาขา',
        filterCardiology: 'โรคหัวใจ',
        filterOrthopedics: 'กระดูกและข้อ',
        filterOncology: 'มะเร็งวิทยา',
        filterNeurology: 'ประสาทวิทยา',
        filterStemCell: 'สเต็มเซลล์',
        filterCosmetic: 'ศัลยกรรมตกแต่ง',
        statusAvailable: 'ว่าง',
        statusBooked: 'เต็ม',
        bookConsultation: 'จองนัดปรึกษา',
        joinWaitlist: 'ขอเข้าคิวรอ',
        noSpecialistsFound: 'ไม่พบแพทย์ที่ตรงกับเงื่อนไข',
        adjustSearch: 'ลองเปลี่ยนคำค้นหาหรือตัวกรอง',
        specialistCtaTitle: 'ยังไม่แน่ใจว่าควรพบแพทย์สาขาไหน?',
        specialistCtaDesc: 'ทีมดูแลของเราพร้อมวิเคราะห์อาการและแนะนำแพทย์ที่เหมาะกับคุณที่สุดจากเครือข่ายของเรา',

        // About page
        ourStory: 'เรื่องราวของเรา',
        aboutTitle1: 'นิยามใหม่ให้กับ',
        aboutTitle2: 'การท่องเที่ยวเชิงสุขภาพ',
        aboutDesc1: 'ก่อตั้งที่กรุงเทพฯ เมื่อปี 2558 Bio Connext เกิดจากความเชื่อที่เรียบง่าย: ผู้ป่วยทุกคนควรได้รับการดูแลสุขภาพระดับโลก โดยไม่ต้องเผชิญกับความยุ่งยาก ความสับสน หรือค่าใช้จ่ายที่เป็นอุปสรรค',
        aboutDesc2: 'เราเชื่อมผู้ป่วยทั่วโลกเข้ากับแพทย์ผู้เชี่ยวชาญระดับนานาชาติ ด้วยความมุ่งมั่นในความหรูหรา ความโปร่งใส และการดูแลที่แท้จริง',
        estYear: 'ก่อตั้งปี 2558',
        estCity: 'กรุงเทพฯ ประเทศไทย',
        yearsExcellence: '10 ปีแห่งความเป็นเลิศ',
        trustedPatients: 'ไว้วางใจโดยผู้ป่วยกว่า 45 ประเทศ',
        patientsServed: 'ผู้ป่วยที่ดูแลแล้ว',
        countriesReached: 'ประเทศที่ให้บริการ',
        specialistPartners: 'แพทย์พันธมิตร',
        averageRating: 'คะแนนเฉลี่ย',
        ourMission: 'พันธกิจของเรา',
        whyWeExist: 'ทำไมเราถึงมีอยู่',
        missionDesc: 'เราอยู่เพื่อขจัดทุกอุปสรรคที่กั้นระหว่างผู้ป่วยกับการดูแลสุขภาพที่พวกเขาสมควรได้รับ ไม่ว่าจะเป็นภาษา การเดินทาง ความโปร่งใสด้านราคา หรือแค่ไม่รู้จะเริ่มต้นจากตรงไหน',
        v1Title: 'ผู้ป่วยต้องมาก่อน',
        v1Desc: 'ทุกการตัดสินใจของเรายึดประโยชน์ของผู้ป่วยเป็นหลัก ไม่ใช่ความสะดวก ไม่ใช่ต้นทุน แต่คือการดูแลที่ดีที่สุด',
        v2Title: 'โปร่งใสทุกขั้นตอน',
        v2Desc: 'เราเชื่อในราคาที่ชัดเจน การประเมินที่ซื่อตรง และการสื่อสารแบบเปิดตลอดกระบวนการดูแลของคุณ',
        v3Title: 'เข้าใจความหลากหลายทางวัฒนธรรม',
        v3Desc: 'ทีมงานหลายภาษาของเราเข้าใจว่าการดูแลที่ดีคือการสื่อสารด้วยภาษาและวัฒนธรรมของผู้ป่วยเอง',
        v4Title: 'ยึดมั่นในหลักฐานทางวิทยาศาสตร์',
        v4Desc: 'เราร่วมงานเฉพาะกับโรงพยาบาลและแพทย์ที่ได้รับการรับรองนานาชาติและมีผลการรักษาที่พิสูจน์แล้ว',
        peopleBehind: 'ทีมงานเบื้องหลัง',
        leadershipTeam: 'ทีมผู้บริหาร',
        partnersLabel: 'พันธมิตรและการรับรองของเรา',
        aboutCtaTitle: 'พร้อมเริ่มต้นแล้วหรือยัง?',
        aboutCtaDesc: 'ร่วมกับผู้ป่วยหลายพันรายที่ไว้ใจให้ Bio Connext ดูแลการตัดสินใจด้านสุขภาพที่สำคัญที่สุดของพวกเขา',
        meetSpecialists: 'พบกับแพทย์ผู้เชี่ยวชาญ',

        // Stats bar
        statPatients: 'ผู้ป่วยที่ดูแลแล้ว',
        statCountries: 'ประเทศ',
        statSpecialists: 'แพทย์ผู้เชี่ยวชาญ',
        statRating: 'คะแนนจากผู้ป่วย',

        // Trust section
        trustLabel: 'ได้รับความไว้วางใจทั่วโลก',
        trustTitle: 'การรับรองมาตรฐานระดับโลก',
        trustDesc: 'เราร่วมงานเฉพาะกับโรงพยาบาลที่ได้รับการรับรองนานาชาติ มั่นใจได้ว่าคุณจะได้รับการดูแลตามมาตรฐานสูงสุดระดับโลก',
        trustJciTitle: 'JCI Accredited',
        trustJciDesc: 'มาตรฐานทองคำด้านคุณภาพและความปลอดภัยของผู้ป่วยทั่วโลก',
        trustIsoTitle: 'ISO 9001:2015',
        trustIsoDesc: 'ระบบการจัดการคุณภาพที่ได้รับการรับรองในทุกการดำเนินงาน',
        trustTemosTitle: 'TEMOS Certified',
        trustTemosDesc: 'การรับรองคุณภาพระดับนานาชาติสำหรับการท่องเที่ยวเชิงสุขภาพ',

        // Testimonials
        testimonialsLabel: 'เสียงจากผู้ป่วย',
        testimonialsTitle: 'ผู้ป่วยของเราพูดอะไร',
        testimonialsDesc: 'ประสบการณ์จริงจากผู้ป่วยที่ไว้วางใจ Bio Connext ในการดูแลสุขภาพ',
        testimonial1Name: 'James Miller',
        testimonial1Location: 'สหรัฐอเมริกา',
        testimonial1Text: 'ตั้งแต่เครื่องบินลงจอดที่กรุงเทพฯ ทีม Bio Connext ทำให้ผมรู้สึกสบายใจมาก การผ่าตัดหัวใจเป็นระดับโลก และการดูแลหลังผ่าตัดดีกว่าทุกอย่างที่เคยได้รับที่บ้าน',
        testimonial2Name: 'Yuki Tanaka',
        testimonial2Location: 'ญี่ปุ่น',
        testimonial2Text: 'ล่ามภาษาญี่ปุ่นที่จัดให้เข้าใจศัพท์ทางการแพทย์ทุกคำ ค่าใช้จ่ายประหยัดได้อย่างน่าทึ่ง จ่ายน้อยกว่าใบเสนอราคาจากโรงพยาบาลในโตเกียวถึง 60%',
        testimonial3Name: 'Sarah Al-Rashid',
        testimonial3Location: 'สหรัฐอาหรับเอมิเรตส์',
        testimonial3Text: 'Bio Connext ประสานงานทุกอย่าง: ตั๋วเครื่องบิน โรงแรม รถรับส่งโรงพยาบาล แม้แต่อาหาร ผลการรักษาสเต็มเซลล์เปลี่ยนชีวิตไปเลย แนะนำอย่างยิ่ง',

        // FAQ Section
        faqTitle: 'คำถามที่พบบ่อย',
        faqSubtitle: 'ทุกสิ่งที่คุณต้องรู้เกี่ยวกับการท่องเที่ยวเชิงสุขภาพในประเทศไทย',
        faq1Q: 'การท่องเที่ยวเชิงสุขภาพในประเทศไทยคืออะไร?',
        faq1A: 'การท่องเที่ยวเชิงสุขภาพในประเทศไทยคือการที่ผู้ป่วยต่างชาติเดินทางมารับบริการทางการแพทย์ในประเทศไทย ประเทศไทยเป็นผู้นำระดับโลกด้านการท่องเที่ยวเชิงสุขภาพ มีโรงพยาบาลที่ได้รับการรับรอง JCI แพทย์ผู้เชี่ยวชาญที่ได้รับใบรับรอง และค่าใช้จ่ายต่ำกว่าประเทศตะวันตก 40–70% Bio Connext ดูแลทุกขั้นตอนตั้งแต่การจับคู่แพทย์จนถึงการพักฟื้นหลังการรักษา',
        faq2Q: 'ค่ารักษาพยาบาลในไทยเทียบกับสหรัฐฯ ต่างกันเท่าไหร่?',
        faq2A: 'การรักษาพยาบาลในประเทศไทยมีค่าใช้จ่ายต่ำกว่าสหรัฐอเมริกา 40–70% เช่น การผ่าตัดหัวใจอาจอยู่ที่ $15,000–$25,000 ในไทย เทียบกับ $70,000–$150,000 ในสหรัฐฯ ศัลยกรรมกระดูก ทันตกรรม และศัลยกรรมความงามก็ประหยัดได้ในระดับเดียวกัน ทั้งหมดในสถานพยาบาลที่ได้รับการรับรอง JCI กับศัลยแพทย์ที่ได้รับการฝึกฝนจากต่างประเทศ',
        faq3Q: 'Bio Connext ให้บริการอะไรบ้าง?',
        faq3A: 'Bio Connext ให้บริการดูแลครบวงจร ได้แก่ จับคู่แพทย์ผู้เชี่ยวชาญจากพันธมิตรกว่า 50 ราย ขอ Second Opinion รับที่สนามบิน รถรับส่ง VIP ล่ามทางการแพทย์กว่า 10 ภาษา ประสานงานประกัน พยาบาลดูแลหลังผ่าตัด จัดหาที่พัก และบริการดูแลตลอด 24 ชั่วโมงทุกภาษา',
        faq4Q: 'โรงพยาบาลในไทยได้รับการรับรองมาตรฐานสากลหรือไม่?',
        faq4A: 'ได้ครับ ประเทศไทยมีโรงพยาบาลที่ได้รับการรับรอง JCI (Joint Commission International) กว่า 60 แห่ง มากที่สุดในเอเชีย Bio Connext ร่วมงานเฉพาะกับสถานพยาบาลที่ได้รับการรับรอง JCI, ISO 9001:2015 และ TEMOS เพื่อให้มั่นใจในมาตรฐานความปลอดภัยและคุณภาพสูงสุด',
        faq5Q: 'รองรับล่ามทางการแพทย์กี่ภาษา?',
        faq5A: 'Bio Connext ให้บริการล่ามทางการแพทย์มืออาชีพกว่า 10 ภาษา ได้แก่ อังกฤษ ไทย จีนกลาง ญี่ปุ่น อาหรับ รัสเซีย เยอรมัน ฝรั่งเศส เกาหลี และสเปน ล่ามทุกคนได้รับการรับรองและมีความเชี่ยวชาญด้านศัพท์ทางการแพทย์',

        // AI Assistant – greeting & suggestions
        aiGreeting: 'สวัสดีครับ! Hello! Ni hao!',
        aiWelcomeMsg: 'ผมคือผู้ช่วยดูแลสุขภาพส่วนตัวของคุณ วันนี้ช่วยอะไรได้บ้างครับ?',
        aiHelpIntro: 'ผมช่วยคุณได้เรื่อง:',
        aiHelpItem1: 'จองนัดพบแพทย์ผู้เชี่ยวชาญ',
        aiHelpItem2: 'จัดรถรับส่ง VIP สนามบิน',
        aiHelpItem3: 'จัดการและแปลเอกสารทางการแพทย์',
        aiHelpItem4: 'ขอ Second Opinion',
        aiHelpItem5: 'ประมาณค่าใช้จ่ายและแพ็กเกจ',
        aiSuggestion1: 'จองนัดแพทย์',
        aiSuggestion2: 'ขอ Second Opinion',
        aiSuggestion3: 'รถรับส่งสนามบิน',
        aiSuggestion4: 'อัปโหลดเอกสาร',
        aiSidebarConsults: 'การปรึกษาล่าสุด',
        aiSidebarProfile: 'โปรไฟล์สุขภาพ',
        aiSidebarRecords: 'เวชระเบียน',
        aiSidebarEmergency: 'เบอร์ฉุกเฉิน',
        aiEmergencyTitle: 'เบอร์ฉุกเฉิน',
        aiEmergencyDesc: 'บริการตลอด 24 ชั่วโมง',

        // AI Assistant page
        aiBrandTagline: 'บริการทางการแพทย์ระดับพรีเมียม',
        aiNewConsult: 'เริ่มการปรึกษาใหม่',
        aiMenuLabel: 'เมนู',
        aiRecentConsults: 'การปรึกษาล่าสุด',
        aiHealthProfile: 'โปรไฟล์สุขภาพ',
        aiMedRecords: 'เวชระเบียน',
        aiViewSpecialists: 'ดูแพทย์ผู้เชี่ยวชาญ',
        aiRecentHistory: 'ประวัติล่าสุด',
        aiBackHome: 'กลับหน้าหลัก',
        aiEmergencyContacts: 'เบอร์ฉุกเฉิน',
        aiOnlineStatus: 'ออนไลน์ · หลายภาษา',
        aiEmergencyBtn: 'ฉุกเฉิน',
        aiYou: 'คุณ',
        aiDrName: 'AI คอนเซียร์จ',
        aiTypePlaceholder: 'อธิบายความต้องการด้านสุขภาพหรือถามคำถาม…',
        aiEncryptedNote: 'เข้ารหัสทุกขั้นตอน · มาตรฐาน HIPAA',
        aiDisclaimerNote: 'AI อาจผิดพลาดได้ — โปรดตรวจสอบข้อมูลสำคัญกับแพทย์',
        aiEmergencyAvailable: 'บริการตลอด 24 ชั่วโมง',
        aiClose: 'ปิด',
        aiToday: 'วันนี้',
        aiYesterday: 'เมื่อวาน',
        aiHistory1: 'ขอ Second Opinion เรื่องหัวใจ',
        aiHistory2: 'ส่งต่อผู้เชี่ยวชาญผิวหนัง',
        aiHistory3: 'สอบถามเรื่องผ่าตัดสะโพก',

        // Pricing page
        pricingNav: 'ราคาแพ็กเกจ',
        pricingHeroTitle: 'ราคาโปร่งใส',
        pricingHeroDesc: 'เลือกแพ็กเกจที่เหมาะกับการรักษาของคุณ ทุกแพ็กเกจรวมการเข้าถึงโรงพยาบาลที่ได้รับการรับรอง JCI และเครือข่ายแพทย์ผู้เชี่ยวชาญ',
        pricingMostPopular: 'ยอดนิยม',
        pricingBasicName: 'Essential',
        pricingBasicPrice: '$2,500',
        pricingBasicDesc: 'เหมาะสำหรับการรักษาทั่วไปพร้อมบริการสนับสนุนมาตรฐาน',
        pricingBasicF1: 'จับคู่กับแพทย์ผู้เชี่ยวชาญ',
        pricingBasicF2: 'รับสนามบิน (รถซีดาน)',
        pricingBasicF3: 'ล่ามทางการแพทย์ (ภาษาอังกฤษ)',
        pricingBasicF4: 'ประสานงานเข้าพักโรงพยาบาล',
        pricingBasicF5: 'ติดตามผลหลังการรักษา (7 วัน)',
        pricingPremiumName: 'Premium',
        pricingPremiumPrice: '$5,500',
        pricingPremiumDesc: 'การดูแลครอบคลุมพร้อมบริการ VIP และผู้ประสานงานส่วนตัว',
        pricingPremiumF1: 'ทุกอย่างใน Essential รวมถึง:',
        pricingPremiumF2: 'VIP รับสนามบิน + ผ่านด่านด่วน',
        pricingPremiumF3: 'รถซีดานหรูรับส่ง (ไม่จำกัด)',
        pricingPremiumF4: 'ผู้ประสานงานหลายภาษาตลอด 24/7',
        pricingPremiumF5: 'พยาบาลดูแลหลังผ่าตัด (1 สัปดาห์)',
        pricingPremiumF6: 'ประสานงานประกันและเบิกจ่าย',
        pricingPremiumF7: 'จัดหาโรงแรม/ที่พัก',
        pricingVipName: 'VIP Concierge',
        pricingVipPrice: '$12,000',
        pricingVipDesc: 'ประสบการณ์ White-Glove สุดพิเศษ ออกแบบเฉพาะคุณ',
        pricingVipF1: 'ทุกอย่างใน Premium รวมถึง:',
        pricingVipF2: 'เฮลิคอปเตอร์/เครื่องบินส่วนตัว',
        pricingVipF3: 'อัปเกรดห้องพักส่วนตัวในโรงพยาบาล',
        pricingVipF4: 'เชฟส่วนตัวและจัดการอาหาร',
        pricingVipF5: 'ที่พักและดูแลครอบครัว',
        pricingVipF6: 'ดูแลฟื้นตัวต่อเนื่อง (30 วัน)',
        pricingVipF7: 'ขอ Second Opinion จากผู้เชี่ยวชาญนานาชาติ',
        pricingVipF8: 'จัดคิวด่วนทุกโรงพยาบาลพันธมิตร',
        pricingSelectPlan: 'เลือกแพ็กเกจ',
        pricingContactUs: 'ติดต่อเรา',
        pricingNoteTitle: 'ยังไม่รวมอะไรบ้าง?',
        pricingNoteDesc: 'ราคาแพ็กเกจครอบคลุมบริการ Concierge เท่านั้น ค่ารักษาพยาบาลจะแตกต่างตามประเภทและโรงพยาบาล ใช้เครื่องมือคำนวณค่าใช้จ่ายเพื่อดูราคาหัตถการ',
        pricingPerPackage: 'ต่อแพ็กเกจ',

        // Payment page
        paymentTitle: 'ยืนยันการจอง',
        paymentOrderSummary: 'สรุปคำสั่งซื้อ',
        paymentPlan: 'แพ็กเกจ',
        paymentTotal: 'รวมทั้งสิ้น',
        paymentMethodTitle: 'เลือกช่องทางชำระเงิน',
        paymentCreditCard: 'บัตรเครดิต / เดบิต',
        paymentPromptPay: 'PromptPay QR',
        paymentBankTransfer: 'โอนเงินผ่านธนาคาร',
        paymentCardNumber: 'หมายเลขบัตร',
        paymentExpiry: 'วันหมดอายุ (MM/YY)',
        paymentCvc: 'CVC',
        paymentCardHolder: 'ชื่อบนบัตร',
        paymentPayNow: 'ชำระเงิน',
        paymentProcessing: 'กำลังดำเนินการ...',
        paymentScanQr: 'สแกน QR ด้วยแอปธนาคาร',
        paymentQrExpiry: 'QR code หมดอายุใน 15 นาที',
        paymentBankName: 'ธนาคาร',
        paymentBankAccount: 'เลขที่บัญชี',
        paymentBankHolder: 'ชื่อบัญชี',
        paymentBankRef: 'อ้างอิง',
        paymentBankInstructions: 'โอนเงินตามจำนวนที่ระบุ ใช้รหัสอ้างอิงด้านบน ส่งสลิปโอนเงินมาที่ contact@bio.techdev.in.th',
        paymentSecure: 'ธุรกรรมทั้งหมดเข้ารหัสและปลอดภัย',
        paymentSuccess: 'ชำระเงินสำเร็จ!',
        paymentSuccessDesc: 'การจองของคุณได้รับการยืนยันแล้ว เราจะติดต่อคุณภายใน 24 ชั่วโมง',
        paymentBackHome: 'กลับหน้าหลัก',
        paymentNoPlan: 'ยังไม่ได้เลือกแพ็กเกจ',
        paymentNoPlanDesc: 'กรุณาเลือกแพ็กเกจจากหน้าราคาก่อน',
        paymentGoToPricing: 'ดูราคาแพ็กเกจ',

        // Footer
        footerDesc: 'คู่ใจในการท่องเที่ยวเชิงสุขภาพนานาชาติและการดูแลสุขภาพระดับพรีเมียม',
        footerServices: 'บริการ',
        footerContact: 'ติดต่อเรา',
        footerAiConcierge: 'AI คอนเซียร์จ',
        footerPrivacy: 'นโยบายความเป็นส่วนตัว',
        footerTerms: 'ข้อกำหนดการใช้บริการ',
        footerCopyright: '© 2568 Bio Connext สงวนลิขสิทธิ์',

        // NotFound page
        notFoundTitle: '404',
        notFoundHeading: 'ไม่พบหน้านี้',
        notFoundDesc: 'หน้าที่คุณค้นหาไม่มีอยู่หรือถูกย้ายแล้ว',
        notFoundHome: 'กลับหน้าหลัก',
        notFoundAi: 'ถาม AI',

        // BookingModal
        bookingSubtitle: 'กรอกข้อมูลของคุณ แล้วเราจะติดต่อกลับ',
        bookingThankYou: 'ขอบคุณครับ!',
        bookingSuccessDesc: 'เราจะติดต่อคุณภายใน 24 ชั่วโมง',
        bookingLabelName: 'ชื่อ-นามสกุล',
        bookingLabelEmail: 'อีเมล',
        bookingLabelPhone: 'เบอร์โทรศัพท์',
        bookingLabelSpecialty: 'อาการ / สาขาเฉพาะทาง',
        bookingSelectSpecialty: 'เลือกสาขาเฉพาะทาง...',
        bookingLabelDate: 'วันที่ต้องการ',
        bookingLabelNotes: 'หมายเหตุเพิ่มเติม',
        bookingErrName: 'กรุณากรอกชื่อ',
        bookingErrEmailReq: 'กรุณากรอกอีเมล',
        bookingErrEmailValid: 'กรุณากรอกอีเมลที่ถูกต้อง',
        bookingErrPhone: 'กรุณากรอกเบอร์โทรศัพท์',
        bookingErrSpecialty: 'กรุณาเลือกสาขาเฉพาะทาง',
        bookingErrDate: 'กรุณาเลือกวันที่',

        // Theme toggle
        themeLight: 'เปลี่ยนเป็นโหมดสว่าง',
        themeDark: 'เปลี่ยนเป็นโหมดมืด',
    },

    cn: {
        // Nav & Layout
        homeNav: '首页',
        services: '服务概览',
        aiAssistant: 'AI 助手',
        specialists: '专家',
        about: '关于我们',
        bookBtn: '预约咨询',
        learnMore: '了解更多',
        langLabel: '语言',

        // Home – Hero
        heroTitle1: '世界级医疗',
        heroTitle2: '礼宾服务',
        heroSubtitle: '体验端到端的奢华患者护理和国际医疗旅游服务，让您安心无忧。',
        premiumCare: '高端服务',
        heroBtn1: '申请第二诊断意见',
        heroBtn2: '我们的服务',

        // Home – Journey
        journeyLabel: '您的护理之旅',
        journeyTitle: '从家到医院的无缝支持',
        journeyDesc: '从您家门口到医院再返回，我们处理每一个后勤细节，让您专注于康复。',
        viewFullJourney: '查看完整旅程',
        step1Title: '抵达前规划',
        step1Desc: '与专家进行远程会诊，并在您离家前根据您的医疗需求制定个性化行程。',
        step2Title: 'VIP入院服务',
        step2Desc: '通过私人通道快速办理入院手续，享用豪华私人套房，以及全天候多语言翻译陪同服务。',
        step3Title: '术后康复护理',
        step3Desc: '全面的随访护理计划、药品送至住所，以及安全的医疗接送回家服务。',

        // Home – International Patient Services
        exclusiveBenefits: '专属福利',
        intlPatientsTitle: '国际患者服务',
        intlPatientsDesc: '我们弥合跨境差距。我们专属的国际团队确保语言不再是障碍，舒适始终是首要任务。',
        airportMeetTitle: '机场迎接服务',
        airportMeetDesc: '专属助手在登机口等候，协助快速通关。',
        medicalInterpTitle: '医疗口译服务',
        medicalInterpDesc: '认证口译员提供超过15种语言服务。',
        vipTransportTitle: 'VIP接送服务',
        vipTransportDesc: '豪华轿车或豪华礼车用于所有本地出行。',
        insuranceLiaisonTitle: '保险协调',
        insuranceLiaisonDesc: '与国际保险公司直接对账协调。',
        viewPackages: '查看礼宾套餐',
        whiteGlove: '白手套服务',
        priorityTransfer: '机场优先接送',
        jciAccred: 'JCI认证',
        jciStandard: '国际质量标准',

        // Home – CTA
        homeCtaTitle: '准备好体验高端护理了吗？',
        homeCtaDesc: '我们的医疗专家随时为您提供全面的第二诊断意见和个性化治疗方案。',
        homeCtaBtn1: '预约咨询',
        homeCtaBtn2: '联系专家',
        homeCtaNote: '24/7全天候运营 • 全球援助中心 • 保密服务',

        // Services page
        servicesHeroTitle: '我们的医疗服务生态系统',
        servicesHeroDesc: '全面的端到端患者管理和高端国际医疗旅游解决方案，根据您的需求量身定制。体验无国界的医疗服务。',
        exploreServices: '浏览服务',
        viewDoctors: '查看医生',
        specializedCareLabel: '专业护理支柱',
        specializedCareDesc: '借助我们整合的高端服务套件，引导您的医疗旅程，为您带来安心和最佳结果。',
        s1Title: '专家协调',
        s1Desc: '利用我们专有的匹配算法，为您精准匹配与您病情完全吻合的世界知名专家。',
        s2Title: '第二诊断意见与评估',
        s2Desc: '专家对诊断进行重新评估，透明的价格比较，确保最佳护理价值和治疗效果。',
        s3Title: '先进疗法',
        s3Desc: '获取前沿治疗方案，包括标准护理中不提供的干细胞疗法和再生医学方案。',
        s4Title: '术后护理',
        s4Desc: '在舒适环境中提供专业护理，确保安全顺利的康复过程，配备24/7监护能力。',
        s5Title: 'VIP后勤服务',
        s5Desc: '无缝旅行安排，包括私人机场接送、上门接送和豪华住宿管理。',
        s6Title: '24/7礼宾支持',
        s6Desc: '专属护理协调员全天候待命，处理任何请求，从翻译到家庭住宿一应俱全。',
        planJourneyTitle: '规划您的医疗之旅',
        planJourneyDesc: '使用我们的互动工具，立即获取您的治疗和礼宾服务费用估算。',

        // Cost Estimator
        ceTitle: '互动费用估算工具',
        ceDesc: '获取您医疗之旅的透明费用估算。',
        ceEstimatedCost: '预计费用',
        ceStep1Title: '您需要哪种类型的医疗服务？',
        ceOrthopedic: '骨科手术',
        ceCardiac: '心脏护理',
        ceStemCell: '干细胞疗法',
        ceCosmetic: '整形美容',
        ceDental: '牙科治疗',
        ceOther: '其他治疗',
        ceStep2Title: '选择礼宾附加服务',
        ceTransportTitle: 'VIP地面交通',
        ceTransportDesc: '机场迎接服务、优先通关及豪华面包车提供所有本地医院接送。',
        ceNursingTitle: '术后护理（1周）',
        ceNursingDesc: '私人注册护士在您的酒店协助康复、用药管理和伤口护理。',
        ceInterpTitle: '专属医疗口译员',
        ceInterpDesc: '母语人士陪同您参加所有会诊并翻译医疗文件。',
        ceStep3Title: '估算完成',
        ceStep3Desc: '这是初步估算。请预约咨询我们的专科医生，以便审查您的实际医疗档案并获取精确报价。',
        ceProceedBtn: '继续预约咨询',
        ceBack: '返回',
        ceContinue: '继续',

        servicesCtaTitle: '准备好开始您的旅程了吗？',
        servicesCtaDesc: '今天联系我们的专属护理团队，获取个性化咨询，让我们处理您医疗护理的复杂事务。',
        contactSupport: '联系支持',
        learnAboutUs: '了解更多关于我们',

        // Specialists page
        ourMedicalTeam: '我们的医疗团队',
        specialistsHeroTitle: '世界级专家',
        specialistsHeroDesc: '我们的国际认证医师网络为每个病例带来数十年的专业经验。浏览并直接联系适合您病情的专家。',
        jciAccredited: 'JCI认证',
        langs15: '15+种语言',
        specialists50Plus: '50+位专家',
        searchPlaceholder: '按姓名或专业搜索...',
        availableNow: '立即可用',
        filterAll: '所有专业',
        filterCardiology: '心脏病学',
        filterOrthopedics: '骨科',
        filterOncology: '肿瘤学',
        filterNeurology: '神经学',
        filterStemCell: '干细胞',
        filterCosmetic: '整形美容',
        statusAvailable: '可用',
        statusBooked: '已预约',
        bookConsultation: '预约咨询',
        joinWaitlist: '加入等待名单',
        noSpecialistsFound: '未找到专家。',
        adjustSearch: '请尝试调整搜索条件或筛选器。',
        specialistCtaTitle: '不确定哪位专家适合您？',
        specialistCtaDesc: '我们的护理团队可以分析您的病情，并从我们的网络中推荐最合适的专家。',

        // About page
        ourStory: '我们的故事',
        aboutTitle1: '重新定义',
        aboutTitle2: '医疗旅游',
        aboutDesc1: '2015年成立于曼谷，Bio Connext源于一个简单的信念：每位患者都应该获得世界级医疗服务，而不受复杂性、困惑或成本障碍的阻碍。',
        aboutDesc2: '我们弥合了国际培训专家与全球需要他们的患者之间的差距——以奢华、透明和真诚人文关怀为承诺。',
        estYear: '成立于2015年',
        estCity: '泰国曼谷',
        yearsExcellence: '十年卓越服务',
        trustedPatients: '被45+个国家的患者信赖',
        patientsServed: '服务患者',
        countriesReached: '覆盖国家',
        specialistPartners: '专家合作伙伴',
        averageRating: '平均评分',
        ourMission: '我们的使命',
        whyWeExist: '我们为何存在',
        missionDesc: '我们的存在是为了消除患者与其应得护理之间的每一个障碍——无论该障碍是语言、后勤、成本透明度，还是仅仅是不知从何开始。',
        v1Title: '患者优先理念',
        v1Desc: '我们的每个决定都以对患者最有利为准则——不是方便，不是成本，而是护理。',
        v2Title: '彻底透明',
        v2Desc: '我们相信清晰定价、诚实评估，以及整个旅程中的开放沟通。',
        v3Title: '文化敏感性',
        v3Desc: '我们的多语言团队明白，优质护理意味着用患者自己的语言和文化与其交流。',
        v4Title: '循证卓越',
        v4Desc: '我们只与具有经过验证的临床记录的国际认证医院和医生合作。',
        peopleBehind: '护理背后的人们',
        leadershipTeam: '我们的领导团队',
        partnersLabel: '我们的合作伙伴与认证',
        aboutCtaTitle: '准备好开始您的旅程了吗？',
        aboutCtaDesc: '加入数千名信任Bio Connext为其最重要健康决策提供导航的患者行列。',
        meetSpecialists: '认识我们的专家',

        // Stats bar
        statPatients: '服务患者',
        statCountries: '覆盖国家',
        statSpecialists: '专家团队',
        statRating: '患者评分',

        // Trust section
        trustLabel: '全球信赖',
        trustTitle: '世界级认证资质',
        trustDesc: '我们仅与获得国际认证的医院合作，确保您获得符合全球最高标准的医疗服务。',
        trustJciTitle: 'JCI认证',
        trustJciDesc: '全球医疗质量和患者安全的金标准。',
        trustIsoTitle: 'ISO 9001:2015',
        trustIsoDesc: '所有运营环节均通过质量管理体系认证。',
        trustTemosTitle: 'TEMOS认证',
        trustTemosDesc: '医疗旅游国际质量保证认证。',

        // Testimonials
        testimonialsLabel: '患者故事',
        testimonialsTitle: '患者评价',
        testimonialsDesc: '来自信赖Bio Connext的患者的真实体验分享。',
        testimonial1Name: 'James Miller',
        testimonial1Location: '美国',
        testimonial1Text: '从我降落在曼谷的那一刻起，Bio Connext团队就让我感到完全放心。我的心脏手术是世界级的，术后护理远超我在美国的任何体验。',
        testimonial2Name: 'Yuki Tanaka',
        testimonial2Location: '日本',
        testimonial2Text: '为我安排的日语翻译对每个医学术语都理解得非常透彻。费用节省令人难以置信——同样的手术，我支付的费用比东京医院的报价低60%。',
        testimonial3Name: 'Sarah Al-Rashid',
        testimonial3Location: '阿联酋',
        testimonial3Text: 'Bio Connext协调了一切：航班、酒店、医院接送，甚至餐饮。干细胞治疗的效果改变了我的生活。我非常推荐他们。',

        // FAQ Section
        faqTitle: '常见问题',
        faqSubtitle: '关于泰国医疗旅游您需要了解的一切',
        faq1Q: '什么是泰国医疗旅游？',
        faq1A: '泰国医疗旅游是指国际患者前往泰国接受医疗服务。泰国是全球医疗旅游的领导者，拥有JCI认证医院、经过认证的专科医生，费用比西方国家低40-70%。Bio Connext为您协调从专家匹配到治疗后康复的全程服务。',
        faq2Q: '泰国的医疗费用与美国相比如何？',
        faq2A: '泰国的医疗费用通常比美国低40-70%。例如，心脏手术在泰国约需$15,000-$25,000，而在美国则需$70,000-$150,000。骨科手术、牙科治疗和整形手术也有类似的节省——全部在JCI认证的机构内由国际培训的外科医生完成。',
        faq3Q: 'Bio Connext提供哪些服务？',
        faq3A: 'Bio Connext提供全方位医疗礼宾服务，包括：从50多位合作伙伴中匹配专科医生、第二诊断意见、机场迎接服务、VIP医疗接送、10多种语言的医疗口译、保险协调、术后护理、住宿安排以及24/7多语言礼宾支持。',
        faq4Q: '泰国的医院是否获得国际认证？',
        faq4A: '是的，泰国拥有超过60家JCI（国际联合委员会）认证医院——数量居亚洲首位。Bio Connext仅与JCI认证、ISO 9001:2015认证和TEMOS认证的医疗机构合作，确保最高标准的患者安全和质量。',
        faq5Q: '医疗口译支持哪些语言？',
        faq5A: 'Bio Connext提供超过10种语言的专业医疗口译服务，包括英语、泰语、普通话、日语、阿拉伯语、俄语、德语、法语、韩语和西班牙语。所有医疗口译员均经过认证，精通医疗术语。',

        // AI Assistant – greeting & suggestions
        aiGreeting: '您好！Sawasdee krub! Hello!',
        aiWelcomeMsg: '我是您的私人医疗礼宾顾问。今天我能如何协助您的健康之旅？',
        aiHelpIntro: '我可以帮助您：',
        aiHelpItem1: '预约专科医生',
        aiHelpItem2: '安排VIP机场接送',
        aiHelpItem3: '处理和翻译医疗文件',
        aiHelpItem4: '申请第二诊断意见',
        aiHelpItem5: '费用估算和礼宾套餐',
        aiSuggestion1: '预约医生',
        aiSuggestion2: '第二诊断意见',
        aiSuggestion3: '机场接送',
        aiSuggestion4: '上传病历',
        aiSidebarConsults: '最近咨询',
        aiSidebarProfile: '我的健康档案',
        aiSidebarRecords: '病历记录',
        aiSidebarEmergency: '紧急联系人',
        aiEmergencyTitle: '紧急联系人',
        aiEmergencyDesc: '全天候24小时',

        // AI Assistant page
        aiBrandTagline: '高端医疗协助服务',
        aiNewConsult: '新建咨询',
        aiMenuLabel: '菜单',
        aiRecentConsults: '最近咨询',
        aiHealthProfile: '我的健康档案',
        aiMedRecords: '病历记录',
        aiViewSpecialists: '查看专科医生',
        aiRecentHistory: '最近历史',
        aiBackHome: '返回首页',
        aiEmergencyContacts: '紧急联系人',
        aiOnlineStatus: '在线 · 多语言',
        aiEmergencyBtn: '紧急',
        aiYou: '您',
        aiDrName: 'AI医疗顾问',
        aiTypePlaceholder: '描述您的医疗需求或提问…',
        aiEncryptedNote: '端对端加密 · 符合HIPAA标准',
        aiDisclaimerNote: 'AI可能出错 — 请向专科医生核实重要医疗信息',
        aiEmergencyAvailable: '全天候24小时',
        aiClose: '关闭',
        aiToday: '今天',
        aiYesterday: '昨天',
        aiHistory1: '心脏第二诊断意见',
        aiHistory2: '皮肤科转诊',
        aiHistory3: '髋关节置换咨询',

        // Pricing page
        pricingNav: '套餐价格',
        pricingHeroTitle: '透明定价',
        pricingHeroDesc: '选择适合您医疗之旅的礼宾套餐。所有套餐均包含JCI认证医院和专家网络的访问权限。',
        pricingMostPopular: '最受欢迎',
        pricingBasicName: 'Essential',
        pricingBasicPrice: '$2,500',
        pricingBasicDesc: '适合标准治疗程序，提供基础支持服务。',
        pricingBasicF1: '专家匹配与转诊',
        pricingBasicF2: '机场接送（经济轿车）',
        pricingBasicF3: '医疗口译（英语）',
        pricingBasicF4: '入院协调',
        pricingBasicF5: '基础随访支持（7天）',
        pricingPremiumName: 'Premium',
        pricingPremiumPrice: '$5,500',
        pricingPremiumDesc: '全方位护理配合VIP物流和专属协调员。',
        pricingPremiumF1: '包含Essential所有内容，另加：',
        pricingPremiumF2: 'VIP机场迎接 + 快速通关',
        pricingPremiumF3: '豪华轿车接送（无限次）',
        pricingPremiumF4: '专属多语言协调员24/7',
        pricingPremiumF5: '术后护理（1周）',
        pricingPremiumF6: '保险协调与账单支持',
        pricingPremiumF7: '酒店/住宿安排',
        pricingVipName: 'VIP Concierge',
        pricingVipPrice: '$12,000',
        pricingVipDesc: '终极白手套医疗体验，完全个性化定制。',
        pricingVipF1: '包含Premium所有内容，另加：',
        pricingVipF2: '私人飞机/直升机接送选项',
        pricingVipF3: '医院私人套房升级',
        pricingVipF4: '私人厨师与饮食管理',
        pricingVipF5: '家属住宿与礼宾服务',
        pricingVipF6: '延长康复支持（30天）',
        pricingVipF7: '国际专家第二诊断意见',
        pricingVipF8: '所有合作医院优先排期',
        pricingSelectPlan: '选择套餐',
        pricingContactUs: '联系我们',
        pricingNoteTitle: '不包含什么？',
        pricingNoteDesc: '套餐价格仅涵盖礼宾服务。实际医疗费用因治疗类型和医院而异。使用我们的费用估算工具了解手术费用。',
        pricingPerPackage: '每套餐',

        // Payment page
        paymentTitle: '完成预订',
        paymentOrderSummary: '订单摘要',
        paymentPlan: '套餐',
        paymentTotal: '总计',
        paymentMethodTitle: '选择支付方式',
        paymentCreditCard: '信用卡 / 借记卡',
        paymentPromptPay: 'PromptPay二维码',
        paymentBankTransfer: '银行转账',
        paymentCardNumber: '卡号',
        paymentExpiry: '有效期 (MM/YY)',
        paymentCvc: 'CVC',
        paymentCardHolder: '持卡人姓名',
        paymentPayNow: '立即支付',
        paymentProcessing: '处理中...',
        paymentScanQr: '使用银行APP扫描二维码',
        paymentQrExpiry: '二维码15分钟内有效',
        paymentBankName: '银行名称',
        paymentBankAccount: '账户号码',
        paymentBankHolder: '账户持有人',
        paymentBankRef: '参考号',
        paymentBankInstructions: '请转账准确金额并使用参考代码。将转账凭证发送至 contact@bio.techdev.in.th 确认。',
        paymentSecure: '所有交易均已加密且安全',
        paymentSuccess: '支付成功！',
        paymentSuccessDesc: '您的预订已确认。我们将在24小时内联系您，开始您的医疗之旅。',
        paymentBackHome: '返回首页',
        paymentNoPlan: '未选择套餐',
        paymentNoPlanDesc: '请先从定价页面选择套餐。',
        paymentGoToPricing: '查看套餐价格',

        // Footer
        footerDesc: '您在国际医疗旅游和高端医疗管理方面值得信赖的合作伙伴。',
        footerServices: '服务',
        footerContact: '联系',
        footerAiConcierge: 'AI礼宾',
        footerPrivacy: '隐私政策',
        footerTerms: '服务条款',
        footerCopyright: '© 2025 Bio Connext. 保留所有权利。',

        // NotFound page
        notFoundTitle: '404',
        notFoundHeading: '页面未找到',
        notFoundDesc: '您要查找的页面不存在或已被移动。',
        notFoundHome: '返回首页',
        notFoundAi: '询问AI助手',

        // BookingModal
        bookingSubtitle: '填写您的信息，我们将与您联系',
        bookingThankYou: '谢谢您！',
        bookingSuccessDesc: '我们将在24小时内与您联系。',
        bookingLabelName: '全名',
        bookingLabelEmail: '电子邮件',
        bookingLabelPhone: '电话号码',
        bookingLabelSpecialty: '病症 / 专科',
        bookingSelectSpecialty: '请选择专科...',
        bookingLabelDate: '首选日期',
        bookingLabelNotes: '附加说明',
        bookingErrName: '请输入姓名',
        bookingErrEmailReq: '请输入电子邮件',
        bookingErrEmailValid: '请输入有效的电子邮件',
        bookingErrPhone: '请输入电话号码',
        bookingErrSpecialty: '请选择专科',
        bookingErrDate: '请选择日期',

        // Theme toggle
        themeLight: '切换到浅色模式',
        themeDark: '切换到深色模式',
    },
};

const LanguageContext = createContext();

const langMap = { en: 'en', th: 'th', cn: 'zh' };

export const LanguageProvider = ({ children }) => {
    const [language, setLanguageState] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem('lang') || 'en';
        }
        return 'en';
    });

    const setLanguage = (lang) => {
        setLanguageState(lang);
        localStorage.setItem('lang', lang);
    };

    // Update <html lang> for screen readers and search engines
    useEffect(() => {
        document.documentElement.lang = langMap[language] || language;
    }, [language]);

    const t = (key) => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
